name: Networks
author: Sefiraat
description: 黏液科技附加 網路 繁體翻譯版.
main: io.github.sefiraat.networks.Networks
website: https://github.com/Sefiraat/Networks
version: ${project.version}
api-version: 1.17
depend:
  - Slimefun
softdepend:
  - InfinityExpansion
commands:
  networks:
    description: /networks
    usage: /networks <sub>